### ISSUE TITLE
Use Secret for Workspace Variables

### ISSUE THREAD

**Issue by ejhayes** [hashicorp/terraform-k8s#112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Related to #2 except for `Secrets`

### Potential Terraform Configuration

Although the existing CRD has been [updated](https://github.com/hashicorp/terraform-k8s/commit/725240c23a7e6223e14adf4f12a60ba35faf1d82#diff-7b59ae0dd0b01704304d0a1245b9a0302bc5e6ccc8b1baed0350906f235a9a0aR84) for all forms of `valueFrom`, the only supported type is currently `configMapKeyRef`. It would be useful if this also supported `secretKeyRef`.

One use case here would be to use outputs from one terraform module to be passed in to another terraform module. This was previously possible when outputs could be added to a `ConfigMap` but is no longer possible now that all module outputs are stored in a secret (see: #80).

```hcl
---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: test-workspace
spec:
  organization: myOrg
  secretsMountPath: "/tmp/secrets"
  module:
    source: "someSource"
  variables:
    - key: some_var
      valueFrom:
        secretKeyRef:
          key: my-secret
          name: secret-name
      sensitive: false
      environmentVariable: false
```

In addition updates to secrets should cause the workspace to be rerun, just like the current behavior with`ConfigMaps`.

**Comment by arybolovlev** [comment]
Hi @ejhayes,

I will go ahead and close this issue since it was implemented in this [PR](https://github.com/hashicorp/terraform-k8s/pull/137).

Thank you.
