### ISSUE TITLE
fresh base image

### ISSUE THREAD

**Issue by nhomble** [hashicorp/terraform-k8s#117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking at the [Dockerfile](https://github.com/hashicorp/terraform-k8s/blob/master/Dockerfile#L18) the base image has already gone stale. I see `3.14.3` available in [dockerhub](https://hub.docker.com/_/alpine?tab=tags).

A dependency bot would be helpful here to keep the image fresh. Even better, it might be worth creating a distroless container.

**Comment by chair6** [comment]
A more recent Alpine version was adopted with the PR linked above, and a new image has been published and tagged as 1.1.1 over at https://hub.docker.com/r/hashicorp/terraform-k8s.

**Comment by nhomble** [comment]
awesome @chair6  - FYI I don't see the release in github or dockerhub

https://hub.docker.com/r/hashicorp/terraform-k8s/tags
