### ISSUE TITLE
Support for Terraform Enterprise

### ISSUE THREAD

**Issue by ryanewk** [hashicorp/terraform-k8s#13]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for on-premise Terraform Enterprise installations. Add ability to configure Address, Path, and HTTP client options.

**Comment by joatmon08** [comment]
A few notations to track efforts for full support of TFE.

1. Updating the endpoint in https://github.com/hashicorp/terraform-k8s/compare/tfe-support#diff-c797509046ea8c4cbeca87c93dcf594eL32 to retrieve the Terraform configuration from `terraformrc`.

1. Supporting airgapped installations of TFE will require some additional testing and module configurations.
