### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [hashicorp/terraform-k8s#167]
**Describe the issue**
In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by sheneska** [comment]
Hi @jongwooo, Thank you for your contribution, however we are currently focused on a new version of the Terraform Cloud Operator for Kubernetes at [hashicorp/terraform-cloud-operator](https://github.com/hashicorp/terraform-cloud-operator), aimed for GA in early November. This new version of the operator will bring a cleaner set of CRDs and support for features such as Agent Pools and deploying agents, Run Tasks, and Workspace Notifications. If you would like to participate in our beta please see our [installation instructions](https://github.com/hashicorp/terraform-cloud-operator#install-beta-version) - any feedback is appreciated!
