### ISSUE TITLE
Add example documentation

### ISSUE THREAD

**Issue by dak1n1** [hashicorp/terraform-k8s#55]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to have more documentation or an example to walk users through creating a workspace using the operator.

**Comment by aareet** [comment]
Document/automate happy path installation, use of operator

**Comment by Redeux** [comment]
Does the new readme satisfy this?
