### ISSUE TITLE
Add Terraform Agent Execution mode as option in workspace CRD.

### ISSUE THREAD

**Issue by vfiftyfive** [hashicorp/terraform-k8s#66]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, first I'd like to say that this operator is quite cool.
Today it seems only possible to leverage workspace remote execution when syncing workspace to Terraform Cloud. We need to interact with backed systems that are hosted on-premises and not exposable to the internet. This means using Terraform Cloud agent and configure the workspace CRD accordingly. So our ask is to add this option in the CRD.

Nic

**Comment by Redeux** [comment]
Thanks for the issue Nic!  I transferred it over to the operator repo for visibility.  This is something we've been discussing internally.  We'll update when we have more.

**Comment by Redeux** [comment]
Related to #63
