### ISSUE TITLE
Doesn't support aws IRSA

### ISSUE THREAD

**Issue by rverma-nsl** [hashicorp/terraform-k8s#97]
As per the documentation, terraform aws providers support IRSA or IAM task roles. https://registry.terraform.io/providers/hashicorp/aws/latest/docs. 

However while using the operator with greetings example, it seems it doesn't do that.

Although, the pod already have required environment variables, When we enforce this by setting the variables in the workspace yaml, it gives file not find exception , but the file exists in the pod.

```
Error: WebIdentityErr: failed fetching WebIdentity token: 
│ caused by: WebIdentityErr: unable to read file at /var/run/secrets/eks.amazonaws.com/serviceaccount/token
│ caused by: open /var/run/secrets/eks.amazonaws.com/serviceaccount/token: no such file or directory
```

**Comment by rverma-nsl** [comment]
One of the mistake I understood is that the temporary credentials are only set for the the workspace sink worker and not actually for the terraform vm. I assumed that the terraform code is being run on the same vm, but that is not the case.

Although one thing which we can do to get a similar result is having a reconciler for the temporary credentials which also sync them in environment variables in tf cloud.

**Comment by daroga0002** [comment]
I dont know how you creating service account but seems you are not mounting a service tokens in Kubernetes (or simply have a wrong mapping under IRSA).

Some docs:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
